### PR TITLE
Translate code primers to german (de)

### LINKED ISSUE #62: Code primer: Deutsch (de)
https://github.com/big-ab-games/robo-instructus-translation#4-code-primer

cc @bert2 @Squirkyy

### PR DESCRIPTION
**Pull request by bert2**
This resolves #62.

@Squirkyy, I'd appreciate a double-check for typos, mistranslations or strange wording :) I added you as a collaborator, so feel free to fix the PR where you see fit.

### CODE REVIEW

**Comment by alexheretic** [comment]
Thanks @bert2 ! I'll leave the pr open for a bit for feedback. I'll also get a in-game render of it for you when I get a sec.

**Comment by Squirkyy** [comment]
I took a look at the translation and it was flawless, but for one single grammar error. I fixed it and it is now ready for the merch in my opinion

**Comment by alexheretic** [comment]
Thanks @bert2 @Squirkyy !

**Comment by alexheretic** [comment]
_de_ requirements on the sans & mono font are pretty similar to _en_ so it should render just fine. This is how it looks:

**Pull request merged**
