### PR TITLE
Chinese (simplified)

### PR DESCRIPTION
**Pull request by MaelColuim**

### CODE REVIEW

**Comment by MaelColuim** [comment]
You're using "k" to denote 1000. I think you should include this in the translation file too. Most languages will still be k but in Chinese (traditional and simplified) it should be 千

**Comment by alexheretic** [comment]
The `k` thing is a bit of a pain, I can maybe add it as a separate translation pair

```
#### suffix to denote "kilo" / 1000 of something
k
千
```

This will work if it's always a suffix, good enough? There's also the, don't use commas etc issues with some language formats. I suppose I don't want to dive too deeply into correctness, but I'm happy to make straightforward improvements.

**Comment by MaelColuim** [comment]
A separate language pair was what I was thinking. I also think it's always
k in other languages. I checked Russian, suspecting that it'll be the only
other awkward one. They use k too, but it's a Cyrillic k. Greek might be
different for the same reason.

I hadn't thought about the dots thing. It's the same as English in Chinese,
but European languages tend to reverse the commas and dots. So 100.000,00
is a hundred thousand point zero. That change might be easy enough to make.
No need for it in the translation pair, just a separate file where it can
be set. Whenever you get a new language you can look up which it is, if
unset, default to the English version (or, assuming that most languages are
European, default to the European standard). Whichever.

**Comment by MaelColuim** [comment]
I've looked into it a bit more.  The decimal separator bit is simple
enough, dots in English and British Languages (e.g. Welsh), and in Asian
languages (except Vietnamese and Indonesian).  Commas elsewhere.

For the thousand separator it isn't as straightforward.  Some "comma"
languages use dots, some use spaces.  I'd recommend the default being
spaces until you know otherwise, since space is pretty universally okay -
and is also the ISO standard.

The other thing I'd mention about suffix prefix stuff is, why not have the
whole sentence in the translation pair document.  with {} for the number,
as you have done elsewhere?

When we do translation stuff at work, that is what we do, as to have
part-sentences is to make a judgement on their grammar.

The same for your "left hand" and "right hand" elements.  Even though it
leads to a bit of repetition with the right hand, it isn't that much,
allows for more flexibility and gives better context.

Anyway.  That's all I had on my mind.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by alexheretic** [comment]
Yeah some of these shouldn't be too hard to add. Generally though I'll wait until people complain because otherwise it probably isn't worth the effort to get perfect.

The `k` thing isn't used in any sentences, it's dynamically added in some cases to the graph labels.

**Pull request merged**
