### PR TITLE
translate remaining keyboard command descriptions

### PR DESCRIPTION
**Pull request by bert2**
This translates the remaining keyboard command descriptions.

### CODE REVIEW

**Comment by alexheretic** [comment]
Ah sorry I didn't expect 2 translations to conflict, I should have checked before merging the other pr.

@bert2 can you look at the merged translation and change any you think aren't quite right?

**Comment by alexheretic** [comment]
@Squirkyy maybe you can agree with @bert2 on which translations make sense.

**Comment by alexheretic** [comment]
Ok I've merged this manually, picking the autocomplete ones. Let me know if I screwed this up or the text can still be improved.

And thanks again for helping!

**Comment by bert2** [comment]
The merge looks good. Happy to help :)

I only think that the current translation for `Navigate by word` feels a little bit clumsy. To my ears, `Wortweise navigieren` sounds a bit smoother than `Durch Wort navigieren`. What do you think, @Squirkyy?

A google search for [`"wortweise" navigieren`](https://www.google.com/search?q=%22wortweise%22+navigieren) gives a few results which are descriptions of the same feature in other software.

**Comment by Squirkyy** [comment]
I totally agree with you @bert2. I just didn't think of that

**Comment by alexheretic** [comment]
Thanks guys, I've added that suggestion in 13895743ebff0f4a6b00f10dabd1d31bd5b204f0

**Pull request closed without merging**
