### PR TITLE
Copied over the suggested changes from simplified

### PR DESCRIPTION
**Pull request by MaelColuim**

### CODE REVIEW

**Comment by alexheretic** [comment]
Thanks! If you get a chance can you also translate the new `{} slower than best` & menu `Credits`?

**Comment by MaelColuim** [comment]
For the comparisons, can I have units to use?

I don't know how to say credits, looked for a translation but a good one
hasn't been forthcoming yet.

**Comment by alexheretic** [comment]
I'm not using units in the english one, so I'd prefer not to in the translations either.

Ok leave _Credits_ for now then.

**Comment by alexheretic** [comment]
Maybe **制作人员** according to https://docs.google.com/spreadsheets/d/135HgMYcRDt6vnJN0d-xFMEZUeWjVbc61ETf8uVwHERE

**Comment by alexheretic** [comment]
I'm going to use that to fill in the credits in the other langs, but presumably that simplified. Is there a trad version?

**Comment by MaelColuim** [comment]
Chinese uses units a bit more in comparisons, but I guess there not
necessary. I'll have a go, and look for a suitable translation for credits
that doesn't mean university credit or something like that.

**Pull request merged**
