### PR TITLE
Update fun.ru.robomarkup

### PR DESCRIPTION
**Pull request by HSteinway**
Completed. Cleared up.

### CODE REVIEW

**Comment by alexheretic** [comment]
Fantastic thank you!

**Comment by alexheretic** [comment]
In game:

**Comment by HSteinway** [comment]
Looks.. normal. =) Btw, what is Mimas-second?)

**Comment by alexheretic** [comment]
> Looks.. normal. =) Btw, what is Mimas-second?)

It's a fictional time unit from the game's universe. Though it is roughly the same as a millisecond running at one of the slower speeds, so it is meant to have the same abbreviation so you can think of them like milliseconds really.

**Pull request merged**
