### PR TITLE
Update en-replace.ru.pairs

### PR DESCRIPTION
**Pull request by HSteinway**
Additions translated. Some changes in a sake of brevity and fun.

### CODE REVIEW

**Comment by HSteinway** [comment]
I'm confused about using the 'phrase' word. What is a phrase? In Russian it's **a few** words, for ex. 'Luke, I'm your father', 'Easy come, easy go' and so on. Not **a** word, or a command.

**Comment by alexheretic** [comment]
> I'm confused about using the 'phrase' word. What is a phrase? In Russian it's a few words, for ex. 'Luke, I'm your father', 'Easy come, easy go' and so on. Not a word, or a command.

_phrase_ means a single piece of work for the interpretor. So `if EXPR` is a phrase it can be a single "word" like a function call, or a binary operator `scan > 0` etc.

I used _phrase_ because it hasn't been used too much in this context, so doesn't have as many overloaded precise meanings in English at least.

**Comment by HSteinway** [comment]
Well, I guess that's ok. =) I can use "команда" или "шаг", but the first one is incorrect, the second is dumb. "Фраза" is a beautiful greek word, so be it.

**Comment by HSteinway** [comment]
> phrase means a single piece of work for the interpretor. So if EXPR is a phrase it can be a single "word" like a function call, or a binary operator scan > 0 etc.

Should you explain that somewhere or it's a common thing to programmers?) I found nothing about it that's why I ask.

**Comment by alexheretic** [comment]
I just assume players will get the gist by playing the game that its a measure of code size. Less code is better and that's really all that's necessary to understand.

Yeah _phrase_ isn't really used elsewhere, maybe there is a better word for it but I don't know one I just used that. So for the translation you can of course use whatever makes sense as "small expression" or "code piece" or whatever.

**Pull request merged**
